name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Xerces lib
      run: sudo apt-get install -y libxerces-c-dev
    - name: make
      run: make
    - name: run app
      run: ./interp test.cmd
      env:
        LD_LIBRARY_PATH: "./libs"
